version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/web.conf:/etc/nginx/conf.d/web.conf:ro
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/www/:/var/www:ro
      - ./config/cert_ssl:/shared/ssl
#      - ./config/imgs:/tmp/img:ro
    links:
      - php
    networks:
      - db_net
#        ipv4_address: 10.24.1.4
  php:
    build:
      context: dockerfiles
      dockerfile: php
    image: repesca/php
    volumes:
      #          - ./config/filterweb/:/code
      #          - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/www/:/var/www:ro
#      - ./config/imgs:/tmp/img:rw
    links:
      - db
    networks:
      - db_net
#        ipv4_address: 10.24.1.3

  db:
    build:
      context: dockerfiles/postgresql
#      dockerfile: .
    image: repesca/postgresql
    ports:
      - target: 5432 # docker port
        published: 5432 # published port
        protocol: tcp
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
#      POSTGRES_DB: institut
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
#    volumes:
#      - ./volumes/postgres/data:/var/lib/postgresql/data
    networks:
      - db_net
##        ipv4_address: 10.24.1.2
  adminer:
    image: adminer
    restart: always
    links:
      - db
    ports:
      - 8080:8080
    networks:
      - db_net
networks:
  db_net:
#    driver: bridge
##    ipam:
##      config:
##        - subnet: 10.24.1.0/24
##          gateway: 10.24.1.1
